DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY
(
    id   INT         NOT NULL,
    name VARCHAR(50) NOT NULL,

    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS GAME;
CREATE TABLE GAME
(
    id       INT         NOT NULL PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    category INT         NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES CATEGORY (id)
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
    id VARCHAR(32) NOT NULL,

    PRIMARY KEY (id),
);