DROP TABLE IF EXISTS CATEGORY CASCADE;
CREATE TABLE CATEGORY
(
    id   INT         NOT NULL,
    name VARCHAR(50) NOT NULL,

    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS GAME CASCADE;
CREATE TABLE GAME
(
    id       INT         NOT NULL PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    category INT         NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES CATEGORY (id)
);

DROP TABLE IF EXISTS MEMBER CASCADE;
CREATE TABLE MEMBER
(
    id            VARCHAR(36)   NOT NULL,
    username      VARCHAR(2000) NOT NULL,
    password_hash VARCHAR(2000) NOT NULL,
    is_admin      BOOLEAN       NOT NULL DEFAULT FALSE,

    PRIMARY KEY (id)
);