// Get all games
GET http://localhost:8080/games
Authorization: Bearer {{jwt}}

###

// Get one specific game
GET http://localhost:8080/games/1
Authorization: Bearer {{jwt}}

// Update one specific game
PUT http://localhost:8080/games/1
Authorization: Bearer {{jwt}}

