// Get all games
GET http://localhost:8080/games
Authorization: Bearer {{jwt}}

###

// Get one specific game
GET http://localhost:8080/games/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

###

// Create a new game
POST http://localhost:8080/games/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "World of Warcraft",
  "categoryId": "e1eec954-6ef4-4926-8183-7575af189f2a"
}

###

// Update one specific game
PUT http://localhost:8080/games/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

{
  "name": "World of Warcraft 2",
  "categoryId": "e1eec954-6ef4-4926-8183-7575af189f2a"
}

###

// Delete one specific and existing game
DELETE http://localhost:8080/games/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

